### ISSUE TITLE
[BDD] 小麥田

### ISSUE THREAD

**Issue by keytsai** [Game-as-a-Service/Machi-Koro-Java#4]

**Comment by keytsai** [comment]
以 BDD 的方式開發小麥田的發動效果
完成一個 Example:
```
given 有銀行(100 coin)、A 玩家(0 coin)及 B 玩家，A 玩家手牌裡有小麥田
when B 玩家擲骰子是1時，系統分配資源後
then A 玩家從銀行獲得1元 (銀行 coin = 99, A 玩家 coin = 1)
```
及小麥田的發動效果單元測試

**Comment by keytsai** [comment]
有點大包，之後會盡量切分開來
- 把 handCard 類別拿掉了，改成直接在 Player 類別裏面用 List 存放持有的 Establishment 及 LandMark
- Dice 類別尚未實作，考慮僅在 Game 類別以一個型別 int 的屬性表示 (currentDicePoint)

再請大家協助 review!

**Comment by akechetaki10736** [comment]
https://github.com/Game-as-a-Service/Machi-Koro-Java/pull/5
