### ISSUE TITLE
[卡牌] 商業中心實作

### ISSUE THREAD

**Issue by keytsai** [Game-as-a-Service/Machi-Koro-Java#68]
卡牌名稱	商業中心 4張
卡牌效果	當你自己骰出 6 這個數字時，你可以與其他玩家交換一間非[重要建築物]的建築物。	
建設所需金額	8

![image](https://user-images.githubusercontent.com/32290488/235363991-0ec8d335-630e-49f4-b9a2-cfb7e1c8e0f6.png)

**Comment by shmily7829** [comment]
![image](https://user-images.githubusercontent.com/32290488/235363971-4b4d1a24-1708-4fef-8d1e-8f1407ca0b07.png)
